version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
    volumes:
      - ./main.py:/app/main.py
      - ./codes_db.txt:/app/codes_db.txt
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - bot-network

  postgres:
    image: postgres:15
    container_name: telegram_bot_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-telegram_bot}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  admin_web:
    build: .
    container_name: telegram_bot_web
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
    volumes:
      - ./admin_web.py:/app/admin_web.py
      - ./templates:/app/templates
    depends_on:
      - postgres
    networks:
      - bot-network
    command: >
      sh -c "python -c 'import os; print(os.listdir(\".\"))' &&
             python -c 'import os; print(os.listdir(\"./templates\"))' &&
             uvicorn admin_web:app --host 0.0.0.0 --port 5000 --reload"

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - admin_web
    networks:
      - bot-network
    restart: unless-stopped

networks:
  bot-network:
    driver: bridge

volumes:
  postgres_data: 